---
title: "SentimentReturnsAnalysis"
author: "Troy Mazerolle"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Clean and Set Up Environment
if(!is.null(dev.list())) dev.off()
cat("/014")
rm(list=ls())
gc()

library(dplyr)
library(quantmod)
```

```{r}
msft_sentiments <- read.csv("googArticleSentiments.csv") %>%
  select(Date, Sentiment) %>%
  mutate(Date = ifelse(Date == "", NA, as.Date(Date, format = "%b %d, %Y"))) %>%
  na.omit() %>%
  mutate(Date = as.Date(Date, origin = "1970-01-01")) %>%
  group_by(Date) %>%
  summarise(Sentiment = mean(Sentiment))
```

```{r}
getSymbols("GOOG")
msft_returns <- as.data.frame(GOOG) %>%
  tibble::rownames_to_column(var = "Date") %>% 
  mutate(Returns = ((GOOG.Close - lag(GOOG.Close)) / lag(GOOG.Close)),
         Date = as.Date(Date)) %>%
  select(Date, Returns) %>%
  na.omit()
```

```{r}
sentiment_threshold <- 0.65

msft_data <- inner_join(msft_sentiments, msft_returns, by = "Date") %>%
  filter(Date >= as.Date("2023-11-03")) %>%
  mutate(Sentiment = lag(Sentiment)) %>%
  na.omit() %>%
  mutate(Sentiment = ifelse(Sentiment >= sentiment_threshold, "POSITIVE", "NEGATIVE"),
         Returns = ifelse(Returns >= 0, "POSITIVE", "NEGATIVE"))


table(Actual = msft_data$Returns, Predicted = msft_data$Sentiment)
print(paste0("Accuracy: ", sum(msft_data$Returns == msft_data$Sentiment) / length(msft_data$Sentiment)))
```




























